# Cloudflare Pages Configuration
name = "ai-lead-scrape"
compatibility_date = "2024-01-01"

# Pages configuration
[build]
command = "cd frontend && npm ci && npm run build"
cwd = ""

[build.upload]
format = "directory"
dir = "frontend/dist"
